version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.2

events:
  build:
    steps:
      - validate:
          type: script
          script:
            - yes > /dev/null &
