version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.2

events:
  build:
    steps:
      - validate:
          type: script
          script:
            - seq 50 | xargs -P0 -n1 timeout 180 yes > /dev/null
